name: Python Tests

on:
  pull_request:
    branches: [ main ]  # Run when someone creates a PR to merge into main

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        working-directory: ./sandbox
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -e ".[test]"

      - name: Run tests
        working-directory: ./sandbox
        run: |
          . .venv/bin/activate
          python -m pytest src/mcp_server_plaid/test -v
